export const ALL_SUPPLIEDITEMS_REQUEST = 'ALL_SUPPLIEDITEMS_REQUEST'//set loading to true
export const ALL_SUPPLIEDITEMS_SUCCESS = 'ALL_SUPPLIEDITEMS_SUCCESS'//data retrieved successfully
export const ALL_SUPPLIEDITEMS_FAIL = 'ALL_SUPPLIEDITEMS_FAIL'      //failure in retrieving data

export const CLEAR_ERRORS = 'CLEAR_ERRORS' //in case clearing errors (after displaying them) is needed

//CREATION OF SUPPLIED ITEM
export const NEW_SUPPLIEDITEMS_REQUEST = 'NEW_SUPPLIEDITEMS_REQUEST'//set loading to true
export const NEW_SUPPLIEDITEMS_SUCCESS = 'NEW_SUPPLIEDITEMS_SUCCESS'//data retrieved successfully
export const NEW_SUPPLIEDITEMS_FAIL = 'NEW_SUPPLIEDITEMS_FAIL'      //failure in retrieving data
export const NEW_SUPPLIEDITEMS_RESET = 'NEW_SUPPLIEDITEMS_RESET'


//UPDATION OF SUPPLIED ITEM
export const UPDATE_SUPPLIEDITEMS_REQUEST = 'UPDATE_SUPPLIEDITEMS_REQUEST'//set loading to true
export const UPDATE_SUPPLIEDITEMS_SUCCESS = 'UPDATE_SUPPLIEDITEMS_SUCCESS'   //data retrieved successfully
export const UPDATE_SUPPLIEDITEMS_FAIL = 'UPDATE_SUPPLIEDITEMS_FAIL'      //failure in retrieving data
export const UPDATE_SUPPLIEDITEMS_RESET = 'UPDATE_SUPPLIEDITEMS_RESET'

//DELETION OF SUPPLIED ITEM
export const DELETE_SUPPLIEDITEMS_REQUEST = 'DELETE_SUPPLIEDITEMS_REQUEST'//set loading to true
export const DELETE_SUPPLIEDITEMS_SUCCESS = 'DELETE_SUPPLIEDITEMS_SUCCESS'   //data retrieved successfully
export const DELETE_SUPPLIEDITEMS_FAIL = 'DELETE_SUPPLIEDITEMS_FAIL'      //failure in retrieving data
export const DELETE_SUPPLIEDITEMS_RESET = 'DELETE_SUPPLIEDITEMS_RESET'

//SINGLE SUPPLIED ITEM
export const SINGLE_SUPPLIEDITEM_REQUEST = 'SINGLE_SUPPLIEDITEM_REQUEST'
export const SINGLE_SUPPLIEDITEM_SUCCESS = 'SINGLE_SUPPLIEDITEMS_SUCCESS'
export const SINGLE_SUPPLIEDITEM_FAIL = 'SINGLE_SUPPLIEDITEMS_FAIL'
export const SINGLE_SUPPLIEDITEM_RESET = 'SINGLE_SUPPLIEDITEMS_RESET'